services:
  - type: web
    name: nursphere
    runtime: static
    buildCommand: npx expo export --platform web --output-dir web-build
    staticPublishPath: web-build
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
